### ISSUE TITLE
Kotlin 2.0.20 未适配

### ISSUE THREAD

**Issue by br3ant** [kanyun-inc/Kace#63]
报错堆栈

org.jetbrains.kotlin.util.FileAnalysisException: Somewhere in file /Users/br3ant/Documents/workspace/android/DeviceFeatureMatrix/devicex/companion/companion/src/main/java/com/huami/watch/companion/account/IDeviceTokenManager.kt: java.lang.AbstractMethodError: Receiver class com.kanyun.kace.compiler.KaceFirSupertypeGenerationExtension does not define or inherit an implementation of the resolved method 'abstract java.util.List computeAdditionalSupertypes(org.jetbrains.kotlin.fir.declarations.FirClassLikeDeclaration, java.util.List, org.jetbrains.kotlin.fir.extensions.FirSupertypeGenerationExtension$TypeResolveService)' of abstract class org.jetbrains.kotlin.fir.extensions.FirSupertypeGenerationExtension.
	at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:62)
	at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverTransformer.transformFile(FirSupertypesResolution.kt:883)
	at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)
	at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:20)
	at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.resolveAndCheckFir(firUtils.kt:76)
	at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.buildResolveAndCheckFirViaLightTree(firUtils.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.compileModuleToAnalyzedFir(jvmCompilerPipeline.kt:319)
	at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.compileModulesUsingFrontendIrAndLightTree(jvmCompilerPipeline.kt:118)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:148)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:464)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:73)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:506)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:675)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1660)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AbstractMethodError: Receiver class com.kanyun.kace.compiler.KaceFirSupertypeGenerationExtension does not define or inherit an implementation of the resolved method 'abstract java.util.List computeAdditionalSupertypes(org.jetbrains.kotlin.fir.declarations.FirClassLikeDeclaration, java.util.List, org.jetbrains.kotlin.fir.extensions.FirSupertypeGenerationExtension$TypeResolveService)' of abstract class org.jetbrains.kotlin.fir.extensions.FirSupertypeGenerationExtension.
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.addSupertypesFromExtensions(FirSupertypesResolution.kt:498)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.resolveSpecificClassLikeSupertypes$lambda$15(FirSupertypesResolution.kt:475)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.resolveSpecificClassLikeSupertypes(FirSupertypesResolution.kt:405)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.resolveSpecificClassLikeSupertypes(FirSupertypesResolution.kt:448)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.visitRegularClass(FirSupertypesResolution.kt:428)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.visitRegularClass(FirSupertypesResolution.kt:228)
	at org.jetbrains.kotlin.fir.declarations.FirRegularClass.accept(FirRegularClass.kt:48)
	at org.jetbrains.kotlin.fir.declarations.impl.FirFileImpl.acceptChildren(FirFileImpl.kt:57)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.visitDeclarationContent(FirSupertypesResolution.kt:416)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.visitFile(FirSupertypesResolution.kt:595)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverVisitor.visitFile(FirSupertypesResolution.kt:228)
	at org.jetbrains.kotlin.fir.declarations.FirFile.accept(FirFile.kt:42)
	at org.jetbrains.kotlin.fir.resolve.transformers.FirSupertypeResolverTransformer.transformFile(FirSupertypesResolution.kt:73)
	... 39 more

**Comment by RicardoJiang** [comment]
我们近期更新一下

**Comment by RicardoJiang** [comment]
2.0.20-1.2.0-SNAPSHOT 版本已发布，可以加上以下 maven 仓库后试试：maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots" }

**Comment by br3ant** [comment]
没有找到这个版本
https://s01.oss.sonatype.org/content/repositories/snapshots/com/kanyun/kace/kace-gradle-plugin/2.0.20-1.2.0/kace-gradle-plugin-2.0.20-1.2.0.pom
https://s01.oss.sonatype.org/content/repositories/snapshots/com/kanyun/kace/kace-gradle-plugin/2.0.20-1.2.0-SNAPSHOT/kace-gradle-plugin-2.0.20-1.2.0-SNAPSHOT.pom

**Comment by RicardoJiang** [comment]
这里：https://s01.oss.sonatype.org/content/repositories/snapshots/com/kanyun/kace/kace-gradle-plugin/2.0.20-1.2.0-SNAPSHOT/

**Comment by br3ant** [comment]
我们的项目 gradle 快照用不了，很奇怪

**Comment by whataa** [comment]
请问非SNAPSHOT版本有发布吗，或者发布在哪个仓库的，找不到2.0.20-1.2.0

**Comment by bwmgd** [comment]
Could not find com.kanyun.kace:kace-runtime:2.0.20-1.2.0-SNAPSHOT.

**Comment by RicardoJiang** [comment]
> Could not find com.kanyun.kace:kace-runtime:2.0.20-1.2.0-SNAPSHOT.

try add maven: maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots" }

**Comment by RicardoJiang** [comment]
> 请问非SNAPSHOT版本有发布吗，或者发布在哪个仓库的，找不到2.0.20-1.2.0

非 snapshot 版本尚未发布，我们近期发布下

**Comment by whataa** [comment]
反馈个不知道是不是这个版本新增的问题（之前的我也没用过）：whiteList对多flavor的支持有些问题，例如：
假设项目有A，B，两个flavor，组合buildType后的variant应该就是 aDebug/Release, bDebug/Release，
假设在b的sourceset里存在一个layout_b.xml，那么通过`kace.whiteList += "layout_b.xml"`后，buildA（例如 ./gradlew assembleADebug）也会把B相关的task依赖进来执行

**Comment by RicardoJiang** [comment]
> 反馈个不知道是不是这个版本新增的问题（之前的我也没用过）：whiteList对多flavor的支持有些问题，例如： 假设项目有A，B，两个flavor，组合buildType后的variant应该就是 aDebug/Release, bDebug/Release， 假设在b的sourceset里存在一个layout_b.xml，那么通过`kace.whiteList += "layout_b.xml"`后，buildA（例如 ./gradlew assembleADebug）也会把B相关的task依赖进来执行

可能通过给 A,B flavor 设置不同的 extension 来规避？比如

```
def taskStr = getGradle().getStartParameter().getTaskRequests().toString()
if (taskStr.contains("B")){
  kace {
    whiteList = listOf("layout_b.xml") 
  }
}
```

**Comment by whataa** [comment]
规避办法倒是有，主要想提的点是没有标准方案，例如支持按variant来指定whitelist

**Comment by RicardoJiang** [comment]
> 请问非SNAPSHOT版本有发布吗，或者发布在哪个仓库的，找不到2.0.20-1.2.0

2.0.20-1.2.0 正式版本已发布
